version: '3.8'

services:
  react-app:
    image: umerbloch/react-app:latest  # Replace with your actual image name and tag
    ports:
      - "90:80"
    networks:
      - react-network
    restart: always

networks:
  react-network:
    driver: bridge
