version: '3.8'

services:
  react-app:
    image: your_image_name:your_tag  # Replace with your actual image name and tag
    ports:
      - "80:80"
    networks:
      - react-network

networks:
  react-network:
    driver: bridge
